### ISSUE TITLE
It is bad ogar

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#100]
Not that ye miss but goes very wrong. much lag,stoppages. etc...

**Comment by Eureka22** [comment]
Can you look at the heap? Is there a memory leak?

**Comment by listenyoumusic** [comment]
For the time being, only 20 % ram, and 33 % cpu,the server has enough resources,

Yes, you can see how there stoppages http://agario.ovh

**Comment by Eureka22** [comment]
Yes it's choppy.

**Comment by listenyoumusic** [comment]
Meanwhile I can do ?

**Comment by vram4** [comment]
Were trying to locate the cause of this problem, please be patient.

**Comment by listenyoumusic** [comment]
Ohh sorry @vram4 I thought you were not aware

**Comment by Eureka22** [comment]
@listenyoumusic Check if the latest version solves your problem :)

**Comment by listenyoumusic** [comment]
@Eureka22 @vram4 yet There is little jerks but 0.5 seconds

check http://agario.ovh

**Comment by vram4** [comment]
@listenyoumusic Are there any errors in the console? Can you also use the "playerlist" command to see if there are too many connections?

**Comment by listenyoumusic** [comment]
http://i.gyazo.com/fafb136abab63a2c59c46622ef18610a.png

**Comment by listenyoumusic** [comment]
maxconnection = 200 change (500)?

**Comment by vram4** [comment]
@listenyoumusic Well, those errors are probably the source of the .5 sec jerks. Also, i meant to ask you to use the "playerlist" command in console so i can see if there are people who are disconnected but are still in the server.

**Comment by listenyoumusic** [comment]
http://i.gyazo.com/75f0f18e80384f5efe7714f1002b31c9.png

**Comment by vram4** [comment]
@listenyoumusic Thanks, i see alot of duplicated connections. Maybe there is a problem with the client itself, as i was unable to reproduce this issue.

**Comment by listenyoumusic** [comment]
Then the problem is mine? If it's mine and I can take action

**Comment by vram4** [comment]
@listenyoumusic No, we dont know that yet, i will run a few tests on the server first, then ill try connecting with your client.

**Comment by vram4** [comment]
@listenyoumusic Its a problem with your client. I was only able to reproduce the bug with duplicating connections when i was using your client. I'll fix it server side though.

**Comment by vram4** [comment]
@listenyoumusic On further inspection, it seems that when your client starts up, 2 connection requests are sent. However, the main problem is that if you connect while you are in game, the previous connection is NOT terminated by the client. Instead, it stays in memory until the client closes his game. I suggest you take a look at that.
