### ISSUE TITLE
Still Trouble with botnames!

### ISSUE THREAD

**Issue by helma27** [vram4/Ogar#102]
I still got these bot names, even i update the script https://github.com/vram4/Ogar/commit/3a9e4fb4739577c479e6dda19dd7e81fc23d1bf3

And here's my screenshot: http://i.imgur.com/HZETp9x.png

Please review it, i'm running on Linux centOS 6 64bit~

**Comment by Eureka22** [comment]
Put `botnames.txt` under the directory where you run `node Ogar`.

**Comment by helma27** [comment]
Wow! Thank's a lot!
It worked! 
Btw, when you release your chat system?
I'am waitting for it!

**Comment by Eureka22** [comment]
@helma27 I can do it really soon after I refine the protocol and clean the code a little bit. But I am thinking whether to add it to the main server side system or not since it only works with my version of client.

**Comment by helma27** [comment]
Great, i'm waitting for the great news!

**Comment by helma27** [comment]
btw, one more question..
when i close my Putty, the server closed the connection, how to keep running the server while the Putty or console closed?

**Comment by Eureka22** [comment]
@helma27 Run your server in `tmux` or `screen`

**Comment by helma27** [comment]
can you show me how to do that? i'am new here..

**Comment by Eureka22** [comment]
@helma27 
```
sudo apt-get tmux
tmux
cd /path/to/Ogar
node Ogar
```
Then you can safely exit PuTTY, after you login again, use `tmux a` get the the terminal back.

**Comment by helma27** [comment]
thank you so much!
I'll try that!

**Comment by dooglus** [comment]
"sudo apt-get install tmux" for the first line - you missed the 'install'
bit.

**Comment by Eureka22** [comment]
Oh yes

**Comment by helma27** [comment]
@dooglus yes, i already install it.
Thank's a lot! it worked! :D

**Comment by helma27** [comment]
umm, i have more question, when i connect again to "tmux a", i lost my control to server or agar.io panel, how to connect it back? SS: http://i.imgur.com/QJ0LYoB.png

**Comment by maixuanhan** [comment]
Why are such questions of linux here? Why don't you search on the internet or ask them on StackOverflow? You make burden on DEV team.

**Comment by helma27** [comment]
Sorry...
