### ISSUE TITLE
gameserver.ini exists in 2 places

### ISSUE THREAD

**Issue by scholtes** [vram4/Ogar#103]
exists in Ogar/ but also exists in Ogar/src/.  Why?

**Comment by vram4** [comment]
The gameserver.ini in /Ogar is used for the windows binary. The gameserver.ini in /Ogar/src is used for the nodejs version

**Comment by themuddfamily2** [comment]
It should be moved...

**Comment by vram4** [comment]
Most people only use 1 of those versions i listed. Just delete the files for the other version that you dont use. If i did move them to the same location, there would be tiny inconveniences for either one of the 2. For example, if i made a folder called "config" in /ogar, people using the node version would have to navigate up a directory to find the config file.

**Comment by themuddfamily2** [comment]
if you just moved them to the same location that would fix this?
