### ISSUE TITLE
chat?

### ISSUE THREAD

**Issue by Jackster35** [vram4/Ogar#105]
Hey vram4, do you think you'll be adding support for in-game chat considering the agar-clone now has it implemented? :+1:

**Comment by vram4** [comment]
I would prefer to keep the features of Ogar limited to things that can be achieved with the vanilla clients.  But if enough people want the feature, i will add it.

**Comment by Jackster35** [comment]
Hmmmm, understandable. I'm sure chat integration won't break vanilla as it'll require the custom client to use it, right?

**Comment by Eureka22** [comment]
@vram4 haha i guess many people would want it :P 
I see players in my server having a lot of fun chatting

**Comment by Jackster35** [comment]
It'll be very good because it'll allow people to actually communicate via the game haha. I really think you should add it vram4 but it's obviously down to you :P

**Comment by Eureka22** [comment]
@Jackster35 actually vram4 wants to do this like a plugin system in which you can easily add certain functionalities.

**Comment by Jackster35** [comment]
@Eureka22 Oh right, that seems pretty awesome :)

**Comment by joery1337** [comment]
People like chatting, but on my server it's used for insulting each other :P.

**Comment by tdmusic** [comment]
Adding a chat would be fantastic, or even implementing the one that @Eureka22 has made.

**Comment by Jackster35** [comment]
I think it'd be awesome, it makes me want to switch fork but I love vram4's and he's always adding more to it

**Comment by tdmusic** [comment]
I agree @Jackster35 I tried @Eureka22 and got a fair bit of lag.

**Comment by Eureka22** [comment]
@tdmusic what kind of lag? Are you using my Ogar server or client?

**Comment by tdmusic** [comment]
@Eureka22 Using both your client and server, was movement for the user (the bots seemed to move fine) Was seeing if i could implement your chat system into this branch but it's beyond my skills :(

**Comment by Eureka22** [comment]
@tdmusic It looks all good on my side. I don't know your problem. And we would add the chat sooner or later. Also, I am improving both the Client and chatting, etc.

**Comment by tdmusic** [comment]
@Eureka22 I can show you if you'd like, i mean the server we're using is beastly so it's definitely not that end :)

**Comment by Eureka22** [comment]
@tdmusic  Sure. btw mine is at http://fxia.me/agar, you can also look at that.

**Comment by tdmusic** [comment]
@Eureka22 

www.thelol.party is mine ill just switch to your server now.

**Comment by m-byte** [comment]
@tdmusic Do you get the lagging only while someone is using the chat function or always? If it's only while using the chat, try lowering the maximum message length in the config file.
Otherwise, it's most likely a bug in the client.

**Comment by modsfabio** [comment]
Implemented and working: http://agar.modszombies.com/

**Comment by Jackster35** [comment]
We understand that it works, we're asking vram4 if he could add it to this fork.

**Comment by modsfabio** [comment]
Oh I see. Well we just need the Chat.js and then modify the PacketHandler.js
That's all

**Comment by Jackster35** [comment]
Oh right, so you could essentially just DYI

**Comment by modsfabio** [comment]
Not difficult at all :+1:

**Comment by Jackster35** [comment]
I seem to be having issues, I'm unable to use the Chat code from m-byte and add it to vram4's

**Comment by Jackster35** [comment]
Okay so using vram4's fork and m-byte's chat source, I get this error:

/home/agarp/svr3/Ogar/src/PacketHandler.js:110
            var packet = new Packet.Chat(this.socket.playerTracker, message);
                         ^
TypeError: undefined is not a function
    at PacketHandler.handleMessage (/home/agarp/svr3/Ogar/src/PacketHandler.js:110:26)
    at WebSocket.emit (events.js:110:17)
    at Receiver.onbinary (/home/agarp/node_modules/ws/lib/WebSocket.js:804:10)
    at /home/agarp/node_modules/ws/lib/Receiver.js:533:18
    at Receiver.applyExtensions (/home/agarp/node_modules/ws/lib/Receiver.js:360:5)
    at /home/agarp/node_modules/ws/lib/Receiver.js:527:14
    at Receiver.flush (/home/agarp/node_modules/ws/lib/Receiver.js:336:3)
    at Receiver.opcodes.2.finish (/home/agarp/node_modules/ws/lib/Receiver.js:538:12)
    at Receiver.expectHandler (/home/agarp/node_modules/ws/lib/Receiver.js:512:33)
    at Receiver.add (/home/agarp/node_modules/ws/lib/Receiver.js:91:24)


Which makes no sense because packet/Chat.js is present.

**Comment by modsfabio** [comment]
Don’t forget to include it in the index.js 

 

 

Von: Jackster35 [mailto:notifications@github.com] 
Gesendet: Samstag, 27. Juni 2015 12:48
An: vram4/Ogar
Cc: modsfabio
Betreff: Re: [Ogar] chat? (#105)

 

Okay so using vram4's fork and m-byte's chat source, I get this error:

/home/agarp/svr3/Ogar/src/PacketHandler.js:110
var packet = new Packet.Chat(this.socket.playerTracker, message);
^
TypeError: undefined is not a function
at PacketHandler.handleMessage (/home/agarp/svr3/Ogar/src/PacketHandler.js:110:26)
at WebSocket.emit (events.js:110:17)
at Receiver.onbinary (/home/agarp/node_modules/ws/lib/WebSocket.js:804:10)
at /home/agarp/node_modules/ws/lib/Receiver.js:533:18
at Receiver.applyExtensions (/home/agarp/node_modules/ws/lib/Receiver.js:360:5)
at /home/agarp/node_modules/ws/lib/Receiver.js:527:14
at Receiver.flush (/home/agarp/node_modules/ws/lib/Receiver.js:336:3)
at Receiver.opcodes.2.finish (/home/agarp/node_modules/ws/lib/Receiver.js:538:12)
at Receiver.expectHandler (/home/agarp/node_modules/ws/lib/Receiver.js:512:33)
at Receiver.add (/home/agarp/node_modules/ws/lib/Receiver.js:91:24)

Which makes no sense because packet/Chat.js is present.

**Comment by Jackster35** [comment]
Yeah, I kinda noticed that haha, thanks man :)

**Comment by m-byte** [comment]
If you still run into Problems, ‎look at my commits to find the code that changed between them. Make sure you reproduce all changes to all files I modified and you should be fine.

**Comment by modsfabio** [comment]
hi

**Comment by Jackster35** [comment]
I got it working m-byte! Thanks man :)

**Comment by vram4** [comment]
@Jackster35 btw what is your server's website?

**Comment by Jackster35** [comment]
What's your email? I'll email you it

**Comment by vram4** [comment]
@Jackster35 helloimpie4@gmail.com

**Comment by m-byte** [comment]
Since these features will not be added to Ogar, I think, this can be closed. Anyone interested in chat, please try https://github.com/m-byte/Cigar
