### ISSUE TITLE
Cannot npm i on windows

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [vram4/Ogar#106]
I've tried npm i --python=python2.7.10 becaus i have python 3.4 in my path and after some waiting I get:

LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\xxx\Ogar\node_modules\ws\node_modules\utf-8-validate\build\validation.vcx
proj]

What should I do? Does it have something to do with me having to run this on linux?

**Comment by vram4** [comment]
If you are on windows, you can just run the server by clicking launch.bat

**Comment by DominikDitoIvosevic** [comment]
Yeah but I'd like to play with the code a bit. Is it linux only?

**Comment by vram4** [comment]
What version of windows are you using?

**Comment by DominikDitoIvosevic** [comment]
I'm on windows 8.1 and have visual studio 2015 rc installed whose libs and compiler are probably used

**Comment by DominikDitoIvosevic** [comment]
Yeah the bufferutil won't install because for some reason it can't find libcpmt.lib

**Comment by vram4** [comment]
I have no idea how to help you with that error then :( Maybe there is an incompatibility with visual studio.  Npm install works fine on windows 7/xp tho.

**Comment by DominikDitoIvosevic** [comment]
For some reason reinstalling nodejs fixed everything
