### ISSUE TITLE
Mac Support?

### ISSUE THREAD

**Issue by larsjuhw** [vram4/Ogar#108]
Is it possible to open this on a Mac? If so, how?

**Comment by Eureka22** [comment]
Absolutely.

**Comment by larsjuhw** [comment]
But how do I start the server?

**Comment by listenyoumusic** [comment]
Install nodejs and run

**Comment by BasvdW22** [comment]
Install Node.js
"npm install ws"
"sudo -s"
"node index.js" in the "src" directory.
