### ISSUE TITLE
Error Error Error !!!

### ISSUE THREAD

**Issue by forumapp28** [vram4/Ogar#111]
http://prntscr.com/7lszcw

**Comment by vram4** [comment]
You have a wrong client version, please use http://agar.io/

**Comment by forumapp28** [comment]
I took the files from there.

Sorry bad english.

**Comment by forumapp28** [comment]
There was no problem in the previous version.

**Comment by vram4** [comment]
Do you have any extensions?

**Comment by forumapp28** [comment]
gameserver.ini

// Command he has issues.

There was no problem in the previous version.

Sorry bad english.

**Comment by forumapp28** [comment]
example

serverMaxConnections = 300 //Default = 64

// no longer issue ?

sorry bad english

**Comment by vram4** [comment]
No, your comment lines have to be on a different line

**Comment by forumapp28** [comment]
He was working in previous versions

**Comment by vram4** [comment]
@forumapp28 Can i see your config file?

**Comment by forumapp28** [comment]
http://prntscr.com/7ltbyi

http://prntscr.com/7ltc44

**Comment by forumapp28** [comment]
// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// leaderboardUpdateClient: How often leaderboard data is sent to the client (1 tick = 50 milliseconds)
serverMaxConnections = 300 //Default = 64
serverPort = 443
serverGamemode = 0
serverBots = 0
serverBotsIgnoreViruses = false
serverViewBase = 1024

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 14000 //Default = 6000
borderTop = 0
borderBottom = 14000 //Default = 6000

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 3 //Default = 20
foodSpawnAmount = 500 //Default = 10
foodStartAmount = 2500 //Default = 100
foodMaxAmount = 3000 //Default = 500
foodMass = 1
virusMinAmount = 30 //Default = 10
virusMaxAmount = 60 //Default = 50
virusStartMass = 100
virusFeedAmount = 6 //Default = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur 
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15

// [Gamemode]
// Custom gamemode settings
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by vram4** [comment]
@forumapp28 I got the same problem as you, but i removed the comment lines that were in the values and it went back to normal. Use this:

// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// leaderboardUpdateClient: How often leaderboard data is sent to the client (1 tick = 50 milliseconds)
serverMaxConnections = 300
serverPort = 443
serverGamemode = 0
serverBots = 0
serverBotsIgnoreViruses = false
serverViewBase = 1024

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 14000
borderTop = 0
borderBottom = 14000

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 3
foodSpawnAmount = 500
foodStartAmount = 2500
foodMaxAmount = 3000
foodMass = 1
virusMinAmount = 30
virusMaxAmount = 60
virusStartMass = 100
virusFeedAmount = 6

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur 
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15

// [Gamemode]
// Custom gamemode settings
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by forumapp28** [comment]
Thanks

**Comment by forumapp28** [comment]
// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// leaderboardUpdateClient: How often leaderboard data is sent to the client (1 tick = 50 milliseconds)
serverMaxConnections = 300 //Default = 64
serverPort = 443
serverGamemode = 0
serverBots = 0
serverBotsIgnoreViruses = false
serverViewBase = 1024

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 14000 //Default = 6000
borderTop = 0
borderBottom = 14000 //Default = 6000

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 3 //Default = 20
foodSpawnAmount = 500 //Default = 10
foodStartAmount = 2500 //Default = 100
foodMaxAmount = 3000 //Default = 500
foodMass = 1
virusMinAmount = 30 //Default = 10
virusMaxAmount = 60 //Default = 50
virusStartMass = 100
virusFeedAmount = 6 //Default = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur 
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15

// [Gamemode]
// Custom gamemode settings
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by forumapp28** [comment]
He was working in the old version

**Comment by vram4** [comment]
Do you remember what "old version" you were using? like the day when you downloaded it?

**Comment by forumapp28** [comment]
There was no problem yesterday.

Sorry bad English.

**Comment by forumapp28** [comment]
the current version is very incorrect output

sorry bad english

**Comment by vram4** [comment]
Yes, i remember i changed something when i included the update for bots.

**Comment by forumapp28** [comment]
Can you fix it ?

**Comment by vram4** [comment]
Well... It was never intended in the first place lol

**Comment by forumapp28** [comment]
Gameserver.ini = http://prntscr.com/7ltl46
Server start = http://prntscr.com/7ltlcf
Game = http://prntscr.com/7ltlv2

There is no such problem in older versions ?

**Comment by forumapp28** [comment]
???

**Comment by Jackster35** [comment]
Just wait, he'll reply in his own time. No need for the "???"
