### ISSUE TITLE
why oh why??

### ISSUE THREAD

**Issue by djhenjin** [vram4/Ogar#114]
In modules/ini.js starting line 98, you are using  a switch statement to compare true/false/null values with null being the last option and no default. You are aware that since you dont do anything on t/f and you do not break from the cases either, no matter which comes up the code in null gets executed. Which since the other two dont do anything is worse than an if statement in terms of execution time.

In all honesty im not sure why there would even be need for an if there in the first place.

**Comment by vram4** [comment]
Meh, its only run once so its not that big of a performance problem. I'll remove it on the next commit.
