### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by exel80** [vram4/Ogar#115]
Can you add proxy support too?
Thanks bro <3 :D

**Comment by Jackster35** [comment]
Could you explain what you mean by proxy support?

**Comment by exel80** [comment]
Websocket using/listing sock4/5 or http proxy.
So you don't have to share your real ip address to people. (ex. if you host server from home)

**Comment by Jackster35** [comment]
Why would you host a server via a proxy? 99.99% of proxies deny binding to ports anyways.

**Comment by exel80** [comment]
Yeah maybe your right. Besides proxies lag server too much.
Thank you Jackster for quick answers
