### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Cixle45** [vram4/Ogar#119]
Screenshot: http://prntscr.com/7mbbj4
root@vps174219:/usr/lib/nodejs/agar# node index.js
[Game] Ogar - An open source Agar.io server implementation
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.

**Comment by Jackster35** [comment]
Change the port in gameserver.ini also, this isn't exactly an error, just user error. You obviously have nginx or something binding to 443 (default port for ogar)

**Comment by Cixle45** [comment]
what will happen?
I changed the port

**Comment by Jackster35** [comment]
It will start? Set it to like 1501 or something. That's a typical Ogar port

**Comment by Cixle45** [comment]
OK Thank You Very Much . 
How can I have boots Meanwhile Server?
