### ISSUE TITLE
Colors are the same?

### ISSUE THREAD

**Issue by joery1337** [vram4/Ogar#124]
After around 1900 players (That played the server, not concurrent) the colors are not randomly generated anymore, and all the colors are the same..

I've seriously no idea how this is possible, but it's really annoying.

![Problem example](http://i.imgur.com/FiuHzJ6.png)

**Comment by Jackster35** [comment]
Just restart the server every now and again? We're always updating our servers keeping up to date with vram4's pushes. I recommend you do too to prevent bugs like these.

**Comment by vram4** [comment]
@joery1337 Unlike any other bug, i have no idea on why this would happen. Did you change your gamemode in the console or any settings in gameserver.ini?

**Comment by joery1337** [comment]
@vram4 No, I didn't change anything. I moved the color array to the function itself and it works just fine after that.

    GameServer.prototype.getRandomColor = function() {
    	var colors = [{'r':235,'b':0,'g':75},{'r':225,'b':255,'g':125},{'r':255,'b':0,'g':215},    {'r':80,'b':240,'g':170},{'r':180,'b':135,'g':90},{'r':195,'b':0,'g':240},{'r':255,'b':140,'g':0},    {'r':80,'b':0,'g':245},{'r':165,'b':0,'g':25},{'r':80,'b':0,'g':145},{'r':55,'b':255,'g':92},{'r':255,'b':0,'g':140}];
        var index = Math.floor(Math.random() * colors.length);
        var color = colors[index];
        return color;
    };
