### ISSUE TITLE
Unclear what Ogar.exe does

### ISSUE THREAD

**Issue by scholtes** [vram4/Ogar#128]
Is the source for Ogar.exe available?  When making a change to any of the *.js files, restarting the server appears to not have any effect whatsoever.  For example, if you modify the GameServer.js from:

"[Game] Ogar - An open source Agar.io....."

to:

"[Game] I changed this string!"

When running Launch, the old text is still visible.  What is Ogar.exe doing?

**Comment by vram4** [comment]
Ogar.exe is a pre compiled binary for windows users so that they do not have to install ws/node. The source files are located in the /src folder, you would need to install nodejs and ws to run from those.

**Comment by scholtes** [comment]
Does that mean that Ogar.exe can be run as a standalone without any of the source files?

**Comment by vram4** [comment]
Yes, you wont be able to edit any of the in game functions though.

**Comment by scholtes** [comment]
Ah, understood. So to make modifications (other than config), one must use node, correct?

**Comment by vram4** [comment]
Yes
