### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#14]
We're having a lot of freezes with last update, though server RAM & CPU okay :
http://gyazo.com/3f14b665132888246e7dffe91ec272fa

No error in consoles, Food parameter is set to 800 ;)

If you want, you can test our server here 
toum.ovh:444

**Comment by vram4** [comment]
I made some changes to the server that should reduce the freezes/lag. Let me know how it works out.

**Comment by s0me-1** [comment]
The server is running for a few hours now, everything seems to be fine.
There's still some small lags, but no more freezes and it's fully playable.

about 30 players are connected with this config :
http://i.gyazo.com/d1b24e0d4609a17ac4d00214b7fa8548.png

Great work !

**Comment by vram4** [comment]
Thanks for the feedback, i'll be closing this issue then.
