### ISSUE TITLE
Sometimes we can eat virus

### ISSUE THREAD

**Issue by Toumaniere** [vram4/Ogar#15]
But we don't explode and we don't grow up :3

**Comment by vram4** [comment]
Yes, if a virus just spawned, you wont be able to explode from it. This is so that a virus doesnt spawn inside of you and instantly pop you. In the future, these viruses will be invisible until they are ready.

**Comment by artuross** [comment]
Why not to check if position is occupied and if is occupied (by player's cell) generate new location?

**Comment by vram4** [comment]
Yes, that was what i was considering doing but then there would be a chance that the position would be occupied and the server would have to loop many times to find a spot. The server already lags with many people on.

**Comment by dungaka** [comment]
The 1st Virus make us explode but the next Virus can eat.

**Comment by artuross** [comment]
@vram4 What is the chancefor this to happen? 1:1000?

**Comment by vram4** [comment]
@artuross Same chance as getting a virus to spawn on top of you, which is quite often if youre big. Regardless, i changed it so it checks for player cell position and so it wont loop endlessly if we get unlucky.

**Comment by dungaka** [comment]
Error when eating 2nd virus:

ReferenceError: cell is not defined
    at Cell.Virus.onConsume (/home/node/Ogar/entity/Virus.js:40:9)
    at GameServer.updateMoveEngine (/home/node/Ogar/GameServer.js:335:19)
    at GameServer.mainLoop (/home/node/Ogar/GameServer.js:217:14)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by vram4** [comment]
Fixed, i didnt have enough time to test the build earlier.
