### ISSUE TITLE
Move config to different file

### ISSUE THREAD

**Issue by topjor** [vram4/Ogar#18]
I am asking to move the config items to a different file because it is much easier to update then. now if changes are made to the server, you have to revert to the original file and wipe your config, update and redo your config again.
I will make a pull request later this weekend, as i don't have time currently

**Comment by Ephemerality** [comment]
It looks like this is getting added in soon, judging from some of the stuff in the latest commit.

**Comment by topjor** [comment]
Okay, if you still need a pull request please let me know

**Comment by vram4** [comment]
I removed the external config file for the non binary version because the config system is still in beta, there could be bugs like values not being read right that hinder the gameplay.

**Comment by vram4** [comment]
Latest commit now has full configuration file support.
