### ISSUE TITLE
Hunger Mode error

### ISSUE THREAD

**Issue by dungaka** [vram4/Ogar#20]
I got error when player Win:

TypeError: Cannot call method 'getName' of undefined
    at Mode.HungerGames.updateLB (/home/node/Ogar/gamemodes/HungerGames.js:128:44)
    at GameServer.mainLoop (/home/node/Ogar/GameServer.js:256:27)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

**Comment by vram4** [comment]
Yeah, it crashes when someone wins.

**Comment by dungaka** [comment]
It will be better if server running in cluster mode, if concurrent user greater than max number player in 1 realm, it'll spawn 1 more realm running in other core. With single core it can serving around 100 players. Cluster mode will serve more.

**Comment by vram4** [comment]
@dungaka That is a good idea, i might add it at the end of this week when i have time.

**Comment by dungaka** [comment]
@vram4 if someone wins, server doesn't start the game again.

**Comment by vram4** [comment]
@dungaka Yes, its a feature im working on at the moment

**Comment by dungaka** [comment]
I've change to this:

HungerGames.prototype.endGame = function(gameServer) {
	gameServer.run = false;
	this.winner = this.tributes[0];
	this.gamePhase = 0;
}

But the winner cell not reset.

**Comment by vram4** [comment]
@dungaka I pushed a fix for this just now. All cells will die after a player wins.

**Comment by dungaka** [comment]
@vram4 Could you check them move engine please, when split some cells, some time the cells move reverse with the mouse

**Comment by vram4** [comment]
@dungaka When did this start happening?

**Comment by dungaka** [comment]
@vram4 Sometime it happened but low frequency from commit #188

**Comment by dungaka** [comment]
This bug was fixed. Closed #20
