### ISSUE TITLE
HungerGame - spectator mode

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#22]
Take this as a suggestion but, in that kind of game, a spectator mode seems important, so dead players can see another thing than a white screen ^^

**Comment by vram4** [comment]
A new spectate system is on its way. In the meantime, ive added some code that will allow you to spectate a random player.

**Comment by Ephemerality** [comment]
Spectate mode has been updated for all modes so you can now switch between players with the Q key.

**Comment by s0me-1** [comment]
Only works for HungerGames mode ;)

**Comment by Ephemerality** [comment]
What do you mean? The latest commit should work in all modes.

**Comment by s0me-1** [comment]
Q don't switch players in FFA Mode

**Comment by Ephemerality** [comment]
Ok. Was gonna say, it seems to work for me! :P
