### ISSUE TITLE
HungerGame - Add bot after a certain waiting time

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#24]
so anyone can play without waiting for 12 members to start :)

**Comment by vram4** [comment]
Soon :)

**Comment by vram4** [comment]
@s0me-1 Added this in latest commit. It is a good suggestion. To use properly, set "tourneyAutoFill" in gameserver.ini to a value higher than 0. This is the amount of seconds (multiplied by 2) the server will wait after the waiting time starts before filling the server with bots. You do not need to have "serverBots" higher than 0 for this work.

**Comment by s0me-1** [comment]
Nice !

**Comment by vram4** [comment]
@s0me-1 Just added that feature in the latest commit.
