### ISSUE TITLE
Sometimes, bots get stuck in the corners

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#26]
And when there's only two bots having the same bug in Hunger Games mode, this is pretty annoying ^^

A solution would be to end the game when there's no more real players in the game.

**Comment by s0me-1** [comment]
I think I was mistaken. Actually that's not in the corner, they're stuck because there isn't anything in sight

**Comment by vram4** [comment]
I noticed this too, but they should normally be moving to a random spot on the map if they cant see anything.

**Comment by s0me-1** [comment]
http://gyazo.com/731572952729f09a12e3dd5db1831840
