### ISSUE TITLE
End HungerGames when there are only bots remaining

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#28]
Bot battle is usefull for tests, but less usefull for playing ^^

**Comment by yrsegal** [comment]
If you want an example implementation of something similar, you can look at my Hardcore gamemode. I have it checking if '_socket' in player.socket. If it isn't there, you've got yourself a bot.

**Comment by vram4** [comment]
I added your commits, but i also changed it so that the game would continue if there was only 1 human player. 9e49312c83d5bb2088bc113782a31ae503eb7341
