### ISSUE TITLE
requirement server

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#30]
What are the minimum requirements go to the game fluid

Sorry for my english I`am spanish

**Comment by vram4** [comment]
You should be able to run ogar + agario smoothly with any computer that runs agario (connected to the vanilla servers) smoothly

**Comment by listenyoumusic** [comment]
If I say but 1GB of RAM 2GB or more

What is the Recommended?

**Comment by dungaka** [comment]
@listenyoumusic on my server it took around 2 Gb Ram and 20 Mb/s bandwidth for 100 CCU, CPU is most important for this.
