### ISSUE TITLE
Server crash on launch

### ISSUE THREAD

**Issue by JBoughter** [vram4/Ogar#32]
I'm unsure why, but I can't seem to get it to run. I'm using the experimental launch method via Windows.
![t](http://puu.sh/il7l1.png)

Maybe I did something wrong, but I don't think there's any steps after "extract, launch".
I do not have node.js installed, as it says I don't need it.

**Comment by Ephemerality** [comment]
That error generally means that the selected port (443 by default) is in use. Skype tends to be the culprit most of the time. If you have Skype running you can close it and try again, or just choose a different port in the gameserver.ini file.

**Comment by JBoughter** [comment]
Thank you very much, I'll try this.

**Comment by JBoughter** [comment]
Finally running, should be fine for now.

**Comment by vram4** [comment]
@JBoughter I would also like to mention that some of the console commands are missing in the windows binary. It will be updated later today when i test the stability of the (new) commands.
