### ISSUE TITLE
Add mother cell

### ISSUE THREAD

**Issue by destruc7i0n** [vram4/Ogar#33]
All info here:
http://www.reddit.com/r/Agario/comments/39f475/todays_experiment/

**Comment by vram4** [comment]
Its still an experimental mode and things there are subject to change anytime.

**Comment by Ephemerality** [comment]
The mother cell was kind of awful anyway. The new 'daughter cell' stuff is pretty neat though.

**Comment by vram4** [comment]
Added in latest commit.
