### ISSUE TITLE
Error: Cannot find module '/home/Ogar'

### ISSUE THREAD

**Issue by Spurlex** [vram4/Ogar#35]
root@ogar:/home# sudo node Ogar

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/Ogar'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by vram4** [comment]
Use the download from my fork.

**Comment by Spurlex** [comment]
I'm using the commands for your fork to clone it.

Used to work until a recent update.

**Comment by vram4** [comment]
It works fine for me, are you sure youre using "git clone git://github.com/vram4/Ogar.git Ogar"?

**Comment by Spurlex** [comment]
I got it working by using sudo. Problem now is http://agar.io/?192.99.84.237:443 seems to just be frozen.

**Comment by Spurlex** [comment]
Never mind turned out changing game mode froze it.

**Comment by vram4** [comment]
Ah i see, gamemodes like hunger games/tournament will freeze all players until a certain amount have joined (and then the game starts).
