### ISSUE TITLE
Please review the guidelines for contributing to this repository

### ISSUE THREAD

**Issue by dooglus** [vram4/Ogar#37]
https://github.com/vram4/Ogar/blob/master/CONTRIBUTING.md has a list of rules about how to format the code, but recent many changes break these rules.

I can go through the code and fix all the deviations - it would help with merging between repositories, but is only useful if the rules are then following in future.

Would that be helpful for me to do or not?

**Comment by vram4** [comment]
I usually try to follow the contribution rules as best as possible, its github that keeps messing up my formatting. Anyways, if you want to fix them, go ahead and create a pull request with the fixes.

**Comment by vram4** [comment]
@dooglus I pushed your commit to my dev branch, thanks for the formatting fixes.
