### ISSUE TITLE
Ghost Cell bug

### ISSUE THREAD

**Issue by dungaka** [vram4/Ogar#42]
After #205 I got too much ghost cell on my server:

http://player.vn/ghostcell.png

Or you can check directly on my server: http://player.vn

**Comment by dungaka** [comment]
Maybe there's bug in spectate mode

**Comment by vram4** [comment]
@dungaka Are you only getting it in spectate mode?

**Comment by dungaka** [comment]
@vram4 I'm still checking for ghost cell but I think it only happend in spectate mode

**Comment by vram4** [comment]
@dungaka This should be fixed in the latest commits
