### ISSUE TITLE
Console not working after some commands

### ISSUE THREAD

**Issue by M44rtenz** [vram4/Ogar#43]
Sometimes when I use a command like "Mass <Username> 100" the console stopts working. The command doesn't get executed and I can't enter a new command.

**Comment by vram4** [comment]
I added 50 bots and spammed the "mass" command over 100 times, but nothing broke. Are you sure you were using the latest version?

**Comment by M44rtenz** [comment]
I'm running the latest version on CentOS 6.5 with Node.js v0.10.38
