### ISSUE TITLE
Problem server close

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#48]
Hi

I Have a problem the server using the command "killed" and closing server

http://i.gyazo.com/2d39d5e19a0fd5a05bd982eba5468fe3.png

**Comment by M64mc** [comment]
And where's the problem?

**Comment by listenyoumusic** [comment]
The server is closed ?

It has happened to me several times

**Comment by M64mc** [comment]
Oh.
Did you do Ctrl+C while it was running? That kills the process.

**Comment by listenyoumusic** [comment]
No.

Every so often jumps on the Server "killed"
and closes the process

**Comment by M64mc** [comment]
Never happened to me. Do you have the latest version?

**Comment by listenyoumusic** [comment]
No, I have prior to this new

**Comment by vram4** [comment]
"Killed" is not a command, you may use "kill [player name]" or "killall". Also make sure you are using the latest version of Ogar and nodejs. Ogar is designed for nodejs 0.12

**Comment by listenyoumusic** [comment]
version node: 0.12.4

The problem is on the rise in ram.
As I can do to go down the ram used in ogar?

**Comment by vram4** [comment]
Ram isnt an issue with Ogar, if it lags, its probably from the browser you are using.
