### ISSUE TITLE
Changing the color of a cell during the game

### ISSUE THREAD

**Issue by izanagi1995** [vram4/Ogar#50]
Hello,
For a gamemode, I need to change the color during the game.
I tried all possible ways (with cell.update() and without cell.update()) but the client doesn't change the color...
Do you know a way to do that without removing the current cell and adding a new cell? 
Thank you.

**Comment by vram4** [comment]
cell.setColor(color) should do the trick. The color parameter is a json object with rgb values.

**Comment by izanagi1995** [comment]
That's it! Thanks!
