### ISSUE TITLE
Setting speed?

### ISSUE THREAD

**Issue by izanagi1995** [vram4/Ogar#51]
Another small question : Can you set the speed of the cell without modifying the game server?

Thanks!

**Comment by vram4** [comment]
Yes, you can change it by overriding the cell function. In your gamemode file, add:

```javascript
var Cell = require('../entity/Cell');

Cell.prototype.getSpeed = function() {
    return [Your custom speed formula here];
};
```

This will replace all player cell's movement speed formula with yours instead. You can do the same thing with the collision event you wanted in the other issue by overriding calcMove() (You will have to copy the functions over though)
