### ISSUE TITLE
Adding onCollide event and cancellable default server behavior

### ISSUE THREAD

**Issue by izanagi1995** [vram4/Ogar#52]
Hello sir,

Can you add a onCollide event? And make the default server behavior cancellable? The gamemode event can return a boolean

```javascript
var defaultBehavior = this.gamemode.onSomeEvent(someParams);
if(defaultBehavior){
    //The server code
}
````

Example : cancelling the eat of a cell

**Comment by vram4** [comment]
See my reply in #51
