### ISSUE TITLE
Cache Node problem

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#53]
Hi...

I have a problem with cache of node when it takes time starts to consume too much ram how could purge nodejs cache?

Sorry for mi English.

**Comment by vram4** [comment]
Do you know exactly how much memory node uses for Ogar on your system? It only uses 32-64 mb of memory on mine.

**Comment by listenyoumusic** [comment]
Ogar not released the memory when and should do

**Comment by listenyoumusic** [comment]
http://i.gyazo.com/8f17389334ef3b53a016085df02afb18.png

**Comment by vram4** [comment]
o.o I have no idea what could be causing that.

**Comment by joery1337** [comment]
After a few hours it uses a lot of ram, arround 900MB.

**Comment by listenyoumusic** [comment]
It is a big problem for Stability

I hope you can solve

**Comment by vram4** [comment]
Theres a memory leak, i dont know whats exactly causing it, but ill look into it when i have time. Im kinda busy this week :/

**Comment by dooglus** [comment]
This is a dup of #63. Let's use that issue to track it.
