### ISSUE TITLE
Installing on Synology NAS not possible

### ISSUE THREAD

**Issue by bentheone** [vram4/Ogar#56]
I tried to install Ogar on my Synology NAS but it isn't working.

Here is my log:
SynologyNAS> npm install
\
> bufferutil@1.1.0 install /volume1/web/agar.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:38:28)
gyp ERR! stack     at E (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:41:29)
gyp ERR! stack     at /volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:52:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:99:15)
gyp ERR! System Linux 3.10.35
gyp ERR! command "node" "/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/web/agar.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

> utf-8-validate@1.1.0 install /volume1/web/agar.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:38:28)
gyp ERR! stack     at E (/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:41:29)
gyp ERR! stack     at /volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/which/which.js:52:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:99:15)
gyp ERR! System Linux 3.10.35
gyp ERR! command "node" "/volume1/@appstore/Node.js/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/web/agar.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing bufferutil@1.1.0
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
ws@0.7.2 node_modules/ws
├── options@0.0.6
└── ultron@1.0.2

Could someone help?

**Comment by Ephemerality** [comment]
The regular Node package won't work.
I can't help much with trying to get it working, but this might point you in the right direction: http://www.gridshore.nl/2011/04/04/installing-node-js-on-my-new-synology/

**Comment by Ephemerality** [comment]
Someone suggested running 'ipkg install make' first, as it looks like it can't find the make tool.

**Comment by bentheone** [comment]
-ash: ipkg: not found

**Comment by Ephemerality** [comment]
Not sure then, your first goal is to figure out how to get the make tool installed. Unless you're able to find/compile a version of ws for whatever architecture the Synology NAS runs on.
