### ISSUE TITLE
Rainbow cells

### ISSUE THREAD

**Issue by Gjum** [vram4/Ogar#57]
The protocol sends a cell's color on every tick. What about adding rainbow cells that change color?

[Inspiration](https://i.imgur.com/jVdHQ6r.gifv)

**Comment by vram4** [comment]
Its possible, i could add this in a separate gamemode.

**Comment by Gjum** [comment]
Nice!

**Comment by vram4** [comment]
Added in latest commit.

**Comment by Gjum** [comment]
Thanks!

> Hint: Use with "setAcid(true)"

Indeed, LOL.
