### ISSUE TITLE
Error when launching .bat file

### ISSUE THREAD

**Issue by Wereman101** [vram4/Ogar#58]
[Game] Ogar - An open source Agar.io server implementation
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at net.js:1280:9
    at dns.js:85:18
    at process._tickCallback (node.js:355:11)

**Comment by listenyoumusic** [comment]
Port not open

**Comment by vram4** [comment]
Close skype or change port number in gameServer.ini, your connection ip will need to be changed to IP:NEWPORT, so if you changed your port to 444, you would need to connect to 127.0.0.1:444 locally.
