### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by vram4** [vram4/Ogar#63]
I've noticed that Ogar is starting to use a lot of memory after a while. A quick look with memwatch told me that the nodes were causing the leak, but i dont know how they were leaking.

**Comment by dooglus** [comment]
You're talking about the server, right?

**Comment by vram4** [comment]
Yes, when i said "nodes", i meant "cells"

**Comment by ryush00** [comment]
Yes. OOM is real. I got "killed".

**Comment by dooglus** [comment]
I've been unable to reproduce. Does it happen in any particular game mode? Does it only happen with multiple players? Only if you split? How long do you have to play before it becomes noticeable?

Can you show me how you used memwatch to see that it's the cells that are causing the problem? I'm new to debugging node memory problems, but would like to learn.

**Comment by vram4** [comment]
I made a branch with my debug code 95ff719c7fa40e80961be4c7c39d8ad91a453316. It doesnt leak as much more, but it still happens.

**Comment by dooglus** [comment]
That's great, thanks.

Any idea why it isn't leaking as much any more? What has changed that might have helped to fix it?

**Comment by vram4** [comment]
I have no idea on how these leaks happen. Maybe its some thing like 944fe0afd4ff3c46bfaf414f9213e8eb96d27015 as it prevents an (non existing) object from being referenced therefore staying in memory, but i could be wrong.

**Comment by dooglus** [comment]
How about d94aa2fee859116a622fd293c6545f3aa963f039 for a possible fix?

I used https://github.com/c4milo/node-webkit-agent and it told me the majority of the leak was due to nodeAdditionQueue increasing forever.

**Comment by dooglus** [comment]
That does seem to be the fix. I can run your 300 bot game now without memory usage growing at all, other than for short periods, and it drops back down again after.

I hadn't seen the bloat because I don't play against bots - it was only affecting bots.

**Comment by vram4** [comment]
Yeah thanks, that seems to be the problem. Actually I forgot to add in the code for bots to process the nodeAdditionQueue when i was rewriting the visibility system.
