### ISSUE TITLE
Experimental Mode 'spawner' cells not spawning mass based on radius

### ISSUE THREAD

**Issue by lurquhar1221** [vram4/Ogar#64]
On my Ogar server, I came over a strange bug.
When purpousfully feeding an experimental cell, it expanded, but the mass kept spawning as if it had never expanded. About a minute later, it had shrunken, and all the spawned mass was revealed.

I have a few modifed values on this server, that make it easier to feed spawners.
Max Cell Count: 200
Starting Mass: 200
Food Size: 5

After coming across this bug, I came here to report it.
I hope it helps.

**Comment by vram4** [comment]
Whoops, I forgot to add that feature in. Currently, they spawn from the center of the mother cell as a test; i planned on having them spawn from the radius.
Btw, you can use "mass [player name] [number]" in the server console to give yourself mass if you want to feed them faster.

**Comment by vram4** [comment]
Fixed in latest commit
