### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#65]
how to the larger map?

**Comment by vram4** [comment]
Change the border values in gameserver.ini

**Comment by listenyoumusic** [comment]
// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000

Change borderRight and borderBottom?

**Comment by vram4** [comment]
Yes
