### ISSUE TITLE
Stability Ogar >100

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#72]
http://i.gyazo.com/48f495954beff70e2b156f04279c5b11.png

From 120 starts to be quite lag when you approach a larger celule

PD: 0 Bots.

My server using Cloud 3 
http://www.ovh.es/vps/vps-cloud.xml

and using 19% ram
30 - 70 Cpu. (ubuntu server 14.10)

**Comment by vram4** [comment]
If it only lags when you are small and go near a large cell, then that is a client problem.
