### ISSUE TITLE
been duplicated connections

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#73]
As it can be seen In the image below, In the game there are just 5
and he tells me ogar 34

http://i.gyazo.com/6fe9a82ba5c7d647c94045c72183e564.png

**Comment by vram4** [comment]
Can you use the command "playerlist" to show all connected players? If people are in the menu or spectating, that counts as a connected player.

**Comment by listenyoumusic** [comment]
http://i.gyazo.com/8e922e63601562d119d38cd89e7cb447.png
