### ISSUE TITLE
player counting without bots

### ISSUE THREAD

**Issue by ryush00** [vram4/Ogar#74]
I can't know how much players joined my server and who is bot.
I think ```status``` command should exclude bots.

**Comment by vram4** [comment]
The console command function will be rewritten soon (Planning on adding custom commands support when creating gamemodes), ill keep your suggestion in mind when i rewrite "status".

**Comment by maixuanhan** [comment]
Viruses are the first number of configured bots/players (_serverBots_) in the list. I think it'll be great if we have names of them too. Also, the *score* seem to be wrong. It's always zero. The score is nothing but the total mass.

**Comment by vram4** [comment]
Added in commit 55b49ffeb6f975a51f133f7b48f38176cd1c5e1f
