### ISSUE TITLE
Update in 17-Jun-2015 causes lag and slow moving

### ISSUE THREAD

**Issue by maixuanhan** [vram4/Ogar#75]
My previous update: 
Jun 15, 2015 
(Refactor spawn code)
955b2da6b661eef6d767d3fd0ad0e8d34f9b9b6a
everything is okay.

My latest update:
Jun 17, 2015 
(Fixed mother cells food spawning mechanics)
a7556e2e67134a2c72b6b17e59d77cedb01fe4a7
cells move laggy and slowly.

I don't know where in the code that causes lag and slow moving.
Do you face the same?

**Comment by maixuanhan** [comment]
I have found out the issue:
The commit 3e734e671f910e5e7d9d8d83c6f904c3da538691 causes laggy when cell moving. Without that fix, cell's moving is OK.

**Comment by dooglus** [comment]
Are you sure?

The code changed in that commit only runs when a cell is consumed.

I'm unable to reproduce the lag. Do you see it when you run the server on your local machine, or only when the server is remote? Does it happen in particular game modes? Only if bots are playing? Any other considerations?

If I can reproduce the problem, I'll fix it.

**Comment by tdmusic** [comment]
I can verify that the game lags pretty badly (unsure whats causing it) It happens with and without bots, currently game mode is FFA.

Bots seem to be able to move freely and the users stutter or freeze.

**Comment by dooglus** [comment]
OK, I see the problem. The code in 3e734e6 is running every time anything gets eaten, but should only be run when a player-controlled cell is eaten.

I'll fix it asap.

**Comment by dooglus** [comment]
Thanks for the bug report, @maixuanhan. I think you'll find it's fixed now.
