### ISSUE TITLE
Bot usernames do not work. [Read]

### ISSUE THREAD

**Issue by SacredMike** [vram4/Ogar#76]
It takes some bots and makes their names like http://i.imgur.com/FW3TR4K.png

**Comment by modsfabio** [comment]
Open botnames.txt with wordpad (not the editor) and save. Then it should work.
This has something todo with the linebreak i think.

**Comment by SacredMike** [comment]
@modsfabio It did not work.

**Comment by modsfabio** [comment]
When you open in notepad.exe, do you see one name per line?

**Comment by SacredMike** [comment]
I do. @modsfabio

**Comment by modsfabio** [comment]
Then it should work. Did you edit the correct botnames.txt?
If everything doesn't work try to make a testfile with 1 name per line and save it using the notepad.

**Comment by SacredMike** [comment]
@modsfabio Still no good...
