### ISSUE TITLE
Splitting motion is odd.

### ISSUE THREAD

**Issue by ryush00** [vram4/Ogar#78]
[Ogar](http://webm.land/w/3kGy/)

[Agar.io](http://webm.land/w/p6fM/)

Ogar's splitting motion is too odd.

**Comment by modsfabio** [comment]
On my server it looks normal.

**Comment by s0me-1** [comment]
Mine too. WHat's your client ?

**Comment by modsfabio** [comment]
Do you mean me? I use the latest client fro Agar.io

**Comment by ryush00** [comment]
Hmm.. I'll check again tomorrow.

**Comment by ryush00** [comment]
http://agar.io/?106.186.123.245:443

I checked and it's not client side's problem.

I using least version of Ogar and still odd.
