### ISSUE TITLE
Last update (19-6-2015) causing lag

### ISSUE THREAD

**Issue by M44rtenz** [vram4/Ogar#81]
This update is causing lag on my server. Anyone else with this problem?

**Comment by tdmusic** [comment]
If anything it's helped reduce the movement lag problem, by a hell of a lot too. What are you running? how many bots and what game mode etc.

**Comment by M44rtenz** [comment]
CentOS 6.5, with Node.JS 0.10. Gamemode is FFA and 10 bots. Before this update everything was fine.

**Comment by vram4** [comment]
Can you post your server's system specs?

**Comment by listenyoumusic** [comment]
I also have the same problem

Using Ubuntu 64 Bits 8 Gb ram, 6 Vcore

**Comment by joery1337** [comment]
Noticed this, the lagg on my server is alot worse then before,
