### ISSUE TITLE
Space Nickname

### ISSUE THREAD

**Issue by forumapp28** [vram4/Ogar#82]
Hello;

Example:

kill Nick Name

It gives an error.

Sorry Bad English.

Thanks..

**Comment by listenyoumusic** [comment]
using "Nick Name"

**Comment by forumapp28** [comment]
Error. Spaces in names.

Example:

kill Forum App

Error :(

Sorry Bad English.

Thanks..

**Comment by Eureka22** [comment]
You can use "" to enclose your nick name :)

**Comment by forumapp28** [comment]
It gives an error ?

**Comment by forumapp28** [comment]
It gives an error ?

**Comment by forumapp28** [comment]
>kill "Forum App28"
[Console] Removed 0 cells
>

Help Me..!

**Comment by maixuanhan** [comment]
The console commands really need updating/enhancements.
