### ISSUE TITLE
Please stability

### ISSUE THREAD

**Issue by listenyoumusic** [vram4/Ogar#83]
For several days Ogar is very lag

**Comment by tdmusic** [comment]
Have you updated the files? A fix was done yesterday for some of the lag.

**Comment by vram4** [comment]
Does it lag on the vanilla servers for you too? Or just ogar?

**Comment by listenyoumusic** [comment]
Ogar

**Comment by vram4** [comment]
Can you describe the lag? Are small cells moving slowly around big ones? Or everything is moving slowy in general? Also can you post your config and system specs?

**Comment by tdmusic** [comment]
Works well for me, especially since the last few updates.

**Comment by listenyoumusic** [comment]
You start with small forms, overall everything moves slow, the client works just slow agar.io

My server has enough resources

http://i.gyazo.com/76fedf14d3d9cd40fb70d91f1096ea88.png
http://i.gyazo.com/7f0da8dc117757b471cbbbf4e83217f4.png

**Comment by vram4** [comment]
Please see 0d39f46ae0fc50aa1963ebda75076bfd64f736cb and leave your feedback.

**Comment by listenyoumusic** [comment]
It goes a little better but lag

**Comment by joery1337** [comment]
This is the same for me.

**Comment by vram4** [comment]
May i get the ip of your servers?

**Comment by joery1337** [comment]
http://agar.yt/

**Comment by vram4** [comment]
@joery1337 It doesnt work for me

**Comment by joery1337** [comment]
@vram4 Works fine for me and some other people, does the page load? Or is there a error message in the debugging console?

**Comment by vram4** [comment]
Now its working

**Comment by vram4** [comment]
@joery1337 Im busy right now, but when i have time, ill add in a console feature to check the delay of the server ticks. You can use that to see if its a server problem.

**Comment by tdmusic** [comment]
That'd be awesome @listenyoumusic What client is that (you have a chat, thats awesome!)

**Comment by dooglus** [comment]
It must be a fork of the server too I guess. vram's server doesn't have chat.

**Comment by tdmusic** [comment]
Thought just as much, pretty impressive (sorry also tagged the wrong person, was meant to tag @joery1337 )

**Comment by Eureka22** [comment]
@joery1337 what server and client side are you using? That's really awesome!

**Comment by listenyoumusic** [comment]
@vram4 http://agario.ovh

**Comment by tdmusic** [comment]
@listenyoumusic Yeah i'm noticing some really bad movement lag, can i ask that all the files are the latest?

**Comment by listenyoumusic** [comment]
If, in the last update
