### ISSUE TITLE
How to type command with forever?

### ISSUE THREAD

**Issue by ryush00** [vram4/Ogar#84]
I'm trying to use [Forever](https://github.com/foreverjs/forever) to rescue from OOM.

But when using Forever, I can't type any command.

Who know how to type command with Forever?

**Comment by Eureka22** [comment]
It seems this topic is not related to this repo.

**Comment by ryush00** [comment]
@Eureka22 just question.

**Comment by listenyoumusic** [comment]
Why no using "screen"?

**Comment by Eureka22** [comment]
screen or tmux is easier :)

**Comment by ryush00** [comment]
"Screen" is die when "out of memory". While "Forever" monitoring it and reduce from server down.

**Comment by Jackster35** [comment]
This is what I use. I throw this in to a screen:

#!/bin/bash

while true
do
    cd ~/svr1
    /usr/local/bin/node ./Ogar
done
