### ISSUE TITLE
Server still eating up all memory.

### ISSUE THREAD

**Issue by Eureka22** [vram4/Ogar#85]
It seems the memory consumption in the console does not match the actual usage.

In console it shows:
\> [Console] Current memory usage: 246246.024/281134.08 kb

In top it shows:
30560 root      20   0 4245692 1.738g   2016 S  34.9 88.9 262:34.28 node               

There is a huge gap. Is that normal? Does this suggest there is still a memory leak?

FYI, the server is on Ubuntu 14.04. It has 50-70 users and run for 8 hours already. 

Thanks!

**Comment by vram4** [comment]
Im investigating this right now

**Comment by modsfabio** [comment]
Same problem here.. Any fix yet?

**Comment by vram4** [comment]
So far in my tests there has been no indacation of a memory leak.

**Comment by Eureka22** [comment]
@vram4 However the memory usage always going up is apparently abnormal. Any pointers toward how we could deal with this problem?

**Comment by modsfabio** [comment]
As soon as the Players stop moving the memory usage stays normal or goes down a bit. If they move again and collect, it goes up and up and up.

**Comment by batbug** [comment]
Running 5 ogar servers on a single dedicated server (ram 4gb) - have no memory leaks at all. ttt.

**Comment by Eureka22** [comment]
@vram4 After switching from node.js 0.10 to node.js 0.12 situation gets much better. I am still doing a memory profiling to see if memory leak really exists.

**Comment by Eureka22** [comment]
## Uncommon memory increase observed.

I did a detailed v8 profile for the memory usage and found something interesting. In the first hour everything was good, and the memory was below 20MB. 

However it suddenly increased to 100+MB within a few minutes as you can see in the picture below.
![1](https://cloud.githubusercontent.com/assets/5158896/8304841/1c1cba12-19dc-11e5-977a-0714fbc4b5dd.png)

I found most of the memory is taken by `smalloc`, they are created but never deleted. 

![2](https://cloud.githubusercontent.com/assets/5158896/8304896/a4a2efa0-19dc-11e5-892e-5916ac42863e.png)

Then I did a timeline tracking for the heap, I found some of the `smalloc` are abnormal, like this one:

![untitled2](https://cloud.githubusercontent.com/assets/5158896/8304911/c80868ee-19dc-11e5-8e64-d2f5d50c317b.png)

Here shows the difference of Snapshot 8 and Snapshot 1, you can find some of them are created but not deleted:
![image](https://cloud.githubusercontent.com/assets/5158896/8304952/24ec9f1c-19dd-11e5-92fd-e1f37b130111.png)

@vram4 Do you have any ideas about that?

**Comment by vram4** [comment]
@Eureka22 Nice job, no wonder i wasnt detecting any leaks with bots. I might have to write my own ws module then :/

**Comment by Eureka22** [comment]
@vram4 I am kind of busy these days, I will have a close look at this problem when I have time. I might try another web socket library and see if that solves the problem.

**Comment by vram4** [comment]
@Eureka22 Sounds good, my email is helloimpie4@gmail.com

**Comment by Eureka22** [comment]
Sent. @vram4

**Comment by vram4** [comment]
@Eureka22 I wrote a java program that would connect to the server with 50 instances. After having the server on for 1.5 hours, i wasnt able to notice anything weird in the memory, the memory usage stayed at around 20 mb.

**Comment by Eureka22** [comment]
wired, what version of nodejs and ws are you using?

Did you make the simulated players move?

**Comment by vram4** [comment]
@Eureka22 They did move, every 10 seconds. I used ws 0.7.2 (the latest) and node 0.12.4

**Comment by Eureka22** [comment]
@vram4 Same version as me, maybe the bug is hard to reproduce, Do you mind sharing with me the debug code and let me test on my server? Totally okay if not :)

**Comment by vram4** [comment]
Yeah sure, ill send it to you via email when i clean up it up a bit, (there are 2 main classes in the program). By the way, whats your server's ip?

**Comment by Eureka22** [comment]
Thanks, I sent that to you via email.

**Comment by Eureka22** [comment]
@vram4 With your client with 50 emulated bots, I was able to reproduce the smalloc cascading problem. That indicates it might be my problem.

**Comment by vram4** [comment]
@Eureka22 Did you have anyone with the web browser clients connected when you did that test, maybe that is what causing the issue.

**Comment by Eureka22** [comment]
@vram4 Exactly what I thought. When I use a separate server with no browser user connected, I was not able to reproduce the problem with simulated bots alone. Only when real players connected that problem will appear. And I thought that was cause by somewhere in the PlayTracker module, can you check that?

**Comment by vram4** [comment]
@Eureka22 I will check later after i finish my work on updating the bots.

**Comment by vram4** [comment]
@Eureka22 I pushed a commit (6fb059c8f5008c3139332b27127f770321e32d8b) that changed a few things in the networking. Since i dont have a server with people on it, can you check and see if it fixes the smalloc problem?

**Comment by Eureka22** [comment]
@vram4 I am testing, tell you the result later.

**Comment by Eureka22** [comment]
Running for an hour without `smalloc` cascading problem. The heap snapshot also looks very promising. But the console outputs several `[Warning] There was an error sending the packet!`. 

I will keep the server running and test the stability.

**Comment by vram4** [comment]
@Eureka22 Thats good to know. The error message is because the server tried to send the packet to a disconnected client. By the way, heres a list of what i changed in that commit if youre curious:
-Disabled "permessage-deflate" packet compression which was only being used by browser clients connected to Ogar, not with my client or browser clients that were connected to the official servers.
-I edited the sendPacket function in gameServer.js so that a buffer object is not created if websocket.readystate was false.

**Comment by Eureka22** [comment]
@vram4 That's an important fix, thank you so much! So previously the problem may be caused by repeatedly creating buffers and attempting to send to disconnected/inactive clients.

**Comment by batbug** [comment]
Ok, sounds good. I will apply this patch to our servers and we test the how the memory usage changes

**Comment by Eureka22** [comment]
@vram4 After running for several hours. 

```
buffer.js:419
    throw new RangeError('attempt to write outside buffer bounds');
          ^
RangeError: attempt to write outside buffer bounds
    at Buffer.write (buffer.js:419:11)
    at Sender.send (/root/node_modules/ws/lib/Sender.hixie.js:54:14)
    at WebSocket.send (/root/node_modules/ws/lib/WebSocket.js:262:18)
    at WebSocket.sendPacket (/root/Ogar/src/GameServer.js:848:14)
    at PlayerTracker.update (/root/Ogar/src/PlayerTracker.js:153:17)
    at GameServer.updateClients (/root/Ogar/src/GameServer.js:360:39)
    at GameServer.mainLoop (/root/Ogar/src/GameServer.js:330:14)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)
```

**Comment by vram4** [comment]
@Eureka22 What about the memory usage?

**Comment by Eureka22** [comment]
@vram4 Memory usage was all good. From 11MB to 20 MB. No `smalloc` issue.

**Comment by vram4** [comment]
@Eureka22 Okay, at least we know thats fixed LOL.

**Comment by Eureka22** [comment]
Cool, but I temporarily changed to old version cause this one is still not so stable. And I am not familiar with `ws` library so I don't know how to fix that.

**Comment by vram4** [comment]
@Eureka22 Alright, looking at your error report, it seems that it is coming from ```this.socket.sendPacket(new Packet.UpdateNodes(this.nodeDestroyQueue.slice(0), updateNodes, nonVisibleNodes));``` in playerTracker.js. It could also be a complication from the new fix.

**Comment by Eureka22** [comment]
might be a complication from the new fix, never seen this before

**Comment by vram4** [comment]
@Eureka22 Yeah, what i think happened was that this was the bug that caused the memory leak. Now instead of a leak, it justs crashes the server. I tried using my debug client with 50 bots for 1 hour and i didnt see any problems, so im adding a try/catch block to the code so that we can see when the error happens again without crashing anything.

**Comment by batbug** [comment]
@vram4 Memory usage was all good. From 11MB to 20 MB. No smalloc issue.

20mb??? How come? My server uses 100mb right at the start and then it goes up and up to about 300mb for 50 connected players.

**Comment by Eureka22** [comment]
@vram4 I tested the latest commit in the afternoon. The bad news is that problem comes again. Probably we just got that luck in the morning. Here is a heap snapshot. 
![1](https://cloud.githubusercontent.com/assets/5158896/8380815/74622736-1c5a-11e5-823f-8169b6ad1fba.png)

And btw the console keeps printing warning non-stop.

**Comment by vram4** [comment]
@Eureka22 Constant warnings means that the socket is closed server side, but the client has not closed the connection yet. I have not found a safe way of terminating the connection yet (socket.close and socket.terminate do not work)

**Comment by vram4** [comment]
@Eureka22 A fix has been applied in the latest commit

**Comment by Eureka22** [comment]
Awesome
