### ISSUE TITLE
Please help me test the Master Server

### ISSUE THREAD

**Issue by vram4** [vram4/Ogar#86]
So I've spent the entire afternoon working on upgrading the master server. The new master server will be able to host many servers in 1 console, create/remove them on the fly, and allow users to switch between game servers without the need to type in an IP. To start the master server, you will need to obtain a copy of the client files. Once you do, open up main_out.js  and find/replace: " aa + 'm.agar.io' " with "http://127.0.0.1:88" (The ip/port of your master server) and " aa + 'm.agar.io/info' " with "http://127.0.0.1:88/info" (the info server). The current files for the master server are available on the MasterServer-Pre-Release branch.

Edit: A feature to 'connect' game servers from different machines to the master server is being worked on. Thinking about using mysql.

**Comment by M64mc** [comment]
# node Ogar --master
[Ogar] An open source Agar.io server implementation
[SyntaxError: Unexpected token o]
[Master] Listening on port 88

/ogar/Ogar/src/index.js:64
    in_.question("<"+selected.server.realmID+">", function(str) {
                                    ^
TypeError: Cannot read property 'realmID' of undefined
    at prompt [as _onTimeout] (/ogar/Ogar/src/index.js:64:37)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by JBoughter** [comment]
Is this for the normal branch or the pre-release branch?

**Comment by vram4** [comment]
It means your master server config is broken, particularly the "regions" value, try redownloading it. If you want to edit the "regions" value, make sure the entire line is surrounded by braces: {}

**Comment by tdmusic** [comment]
So essentially we could start packaging client files and rune FFA and team on the same server? If so that's really cool.

**Comment by vram4** [comment]
@tdmusic Yes

**Comment by M64mc** [comment]
I didn't edit anything. Just downloaded and ran.

**Comment by tdmusic** [comment]
I'm looking for them too, finding that i can't connect to the server from the agar.io/?SERVER:IP now.
