### ISSUE TITLE
Cells only appears if its center is on the screen

### ISSUE THREAD

**Issue by s0me-1** [vram4/Ogar#9]
This can be very frustrating if you're too small to see them :/

**Comment by vram4** [comment]
This is a feature, to prevent cheaters from people with zoom mods from seeing more of the map than they should

**Comment by s0me-1** [comment]
Well, thank you a lot ! :)

And BTW Ty for your work, Ogar is providing tons of fun in our universities ! ^^

**Comment by s0me-1** [comment]
is there a way to disable this feature since agario extended is dead ?

**Comment by vram4** [comment]
I havent added a way to disable the feature yet, but if it was disabled, it would cause alot of lag, both server and client side.

**Comment by s0me-1** [comment]
So extending "serverViewBase" is the only way I guess :)

Ty for your answer !

**Comment by vram4** [comment]
We removed that config field in the last few updates but im planning on adding it back in the next update. I would highly recommend against extending it unless you guys have godly computers.

**Comment by s0me-1** [comment]
Actually the problem we have is that sometimes, if you're a small cell, big cells are spawning on the screen, sometimes taking the half of the screen instantly, and so you crash yourself in the bigger cells because you didn't see it in time... Il try to record the situation to show you that

**Comment by vram4** [comment]
Ah i see, well, i'll have to improve the detection later.

**Comment by vram4** [comment]
@s0me-1 I changed the algorithm so that the server checks if any corner of the cell appears on the screen instead of just the center point.

**Comment by s0me-1** [comment]
We'll test this evening !

**Comment by s0me-1** [comment]
FUlly working with commit https://github.com/vram4/Ogar/commit/1a4ee30eac40b9ace3d222d5f7f02d543b73dac3

we didn't tested the last one yet !
