### ISSUE TITLE
Non-random teams

### ISSUE THREAD

**Issue by batbug** [vram4/Ogar#90]
Hello. I'd like to modify TEAMS mode. 
Right now teams are assigned randomly.
player.team = Math.floor(Math.random() * this.teamAmount);
But how can I assign team based on a player name?

Teams.prototype.onPlayerInit = function(player) { }

here the 'player' doesnot have the player name yet.

Any ideas?

**Comment by Eureka22** [comment]
Maybe we can assign player to team "foo" if he has name "[foo]bar". Then the players can choose with team to join.

**Comment by vram4** [comment]
Right after the player name packet is handled, the cell is spawned. You can edit it in 
```javascript
Teams.prototype.onPlayerSpawn = function(gameServer,player) {
    // Random color based on team
    player.color = this.getTeamColor(player.team);
    // Spawn player
    gameServer.spawnPlayer(player);
};
```
Replace ```player.color = this.getTeamColor(player.team);``` with your own function

**Comment by batbug** [comment]
>> Maybe we can assign player to team "foo" if he has name "[foo]bar". Then the players can choose with team to join.
Yes, this is exactly my idea

>>Right after the player name packet is handled, the cell is spawned. You can edit it in 
Ok, i'll try. 

Thank you

**Comment by vram4** [comment]
Heres an example based on @Eureka22 's repsone:
```javascript
Teams.prototype.onPlayerSpawn = function(gameServer,player) {
    // CUSTOM CODE
    if (player.name.indexOf('[foo]' != -1)) {
        team = 1; // Grean team
    }
    // Random color based on team
    player.color = this.getTeamColor(player.team);
    // Spawn player
    gameServer.spawnPlayer(player);
};
```

**Comment by Eureka22** [comment]
thanks! @vram4

**Comment by batbug** [comment]
just checked. 
at Teams.prototype.onPlayerSpawn = function(gameServer,player) {}
the 'player'.name is empty

**Comment by vram4** [comment]
After looking at the code, thats because ```client.setName(newNick);``` is ahead of the spawn function. Sorry about that, ill push a commit right away.

**Comment by batbug** [comment]
Oh really? That would be great) Thank you)))

**Comment by vram4** [comment]
Pushed a commit, check if it works.

**Comment by batbug** [comment]
ok. one moment...

**Comment by batbug** [comment]
Yeeeaaaaaaaaaahhh It works now! Thank you so much)) Now we can make TEAMS mode better for players!
