### ISSUE TITLE
Linux server

### ISSUE THREAD

**Issue by toma1212** [vram4/Ogar#93]
Hey!

I will wish to make a Agario server on Linux.
Can you explain the process?

Sincerely,
Tom

**Comment by listenyoumusic** [comment]
-> wget http://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
-> tar zxvf node-v0.12.4.tar.gz
->cd node-v0.12.4/
-> ./configure
-> make install

**Comment by listenyoumusic** [comment]
and npm install ws
