### ISSUE TITLE
No external way of getting stats?

### ISSUE THREAD

**Issue by Jackster35** [vram4/Ogar#99]
Hi, is there a way of grabbing the stats of the server via the web socket or anything? Would be handy so we can use php to get the amount of players for IRC or something. Thanks :)

**Comment by vram4** [comment]
The masterserver branch contains the files needed to show server stats (such as player amount).

**Comment by Jackster35** [comment]
Will you be introducing it to this version?

**Comment by vram4** [comment]
Probably not, its going to stay in its own branch.

**Comment by Jackster35** [comment]
Okay, thanks :p
